version: '3.7'

services:

  mongo:
    image: mongo
    container_name: tg_bot_mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: tg_bot_mongo_db
      MONGO_INITDB_ROOT_USERNAME: tg_bot_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: tg_bot_mongo_password
